### ISSUE TITLE
OrderBook延迟

### ISSUE THREAD

**Issue by happysammy** [JiaoziMatrix/aioquant#3]
你这个Market模块如果订阅huobi全部币种的OrderBook, 由于数据量比较多，接收到的行情数据会有延迟。

**Comment by Demon-Hunter** [comment]
@happysammy 
如果订阅品种太多，数据量太大，确实会有一定延迟，从底层硬件来说可能都会有带宽瓶颈。
这里可以分开订阅，比如你订阅100个交易对，那么你可以分成5个进程，每个进程订阅20个，分布式处理，就可以了。

**Comment by happysammy** [comment]
基本都是多进程处理，在一个进程里面即使分组订阅(假设5个symbol一组)， 开多个websockeket连接，行情还是会延迟，感谢分享！
